services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-app-net
    env_file:
      - ./env/mysql.env

  todo-app:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/opt/program
    networks:
      - todo-app-net
    env_file:
      - ./env/backend.env
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    networks:
      - todo-app-net
    volumes:
      - ./frontend:/usr/share/nginx/html
      - /usr/share/nginx/html/node_modules 
    depends_on:
      - todo-app

volumes:
  mysql-data:

networks:
  todo-app-net:
    driver: bridge
